language: go

env:
  - GO111MODULE=on

go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

notifications:
  email: false

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
before_install:
  - go get -v -d ./... && go mod verify

install: true

script:
  - go test -coverprofile=coverage.out -covermode=atomic -p 1 ./...

after_success:
  - curl https://deepsource.io/cli | sh
  - ./bin/deepsource report --analyzer test-coverage --key go --value-file ./coverage.out
